version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env    # or move your .env here if you prefer
    volumes:
      - ./backend:/app                # live‑reload on code change (dev only)
    ports:
      - "${BACKEND_PORT:-8001}:8000"  # host:container
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env               # if you have frontend‑specific vars
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "${FRONTEND_PORT:-8282}:80"   # host:container
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge