version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    # Dev mount for live‑reload; you can keep this in DEV only
    volumes:
      - ./backend:/app
      # Persistent volume for the SQLite file
      - backup-data:/app/db/db.sqlite3
    ports:
      - "${BACKEND_PORT:-8001}:8000"
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    # Dev mount for static content—read‑only
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "${FRONTEND_PORT:-8282}:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  backup-data:
    driver: local
