name: Deploy-Workflow

on:
  push:
    branches:
      - "conduit-docker"

permissions:
  contents: read        # for checkout
  packages: write       # for GHCR

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out code & submodules
        uses: actions/checkout@v4
        with:
          # pull in backend/ and frontend/ submodules
          submodules: recursive
          fetch-depth: 0

      - name: Set up QEMU (optional, multi‑arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file:    ./backend/Dockerfile            # explicit path
          push:    true
          tags: |
            ghcr.io/dinefgh/conduit-backend:latest

      - name: Build & push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file:    ./frontend/Dockerfile           # explicit path
          push:    true
          tags: |
            ghcr.io/dinefgh/conduit-frontend:latest

  deploy:
    name: Deploy to Remote Server
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Check out code & submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # optional: skip host‑key prompt
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          port:     ${{ secrets.SSH_PORT || '22' }}
          source:   "docker-compose.yml"
          target:   "${{ secrets.DEPLOY_PATH }}/" 

      - name: Pull new images & restart
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          port:     ${{ secrets.SSH_PORT || '22' }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            docker compose pull
            docker compose up -d
            